# -*- mode: ruby -*-
# vi: set ft=ruby :

Vagrant.require_version ">= 1.6.2"

Vagrant.configure("2") do |config|
    config.vm.box = "vmware-windows"
    config.vm.guest = :windows
    config.vm.boot_timeout = 500
    config.vm.communicator = "winrm"
    config.winrm.username = "vagrant"
    config.vm.network "forwarded_port", guest: 3389, host: 3389, auto_correct: true
    config.vm.network "forwarded_port", guest: 5995, host: 5995, id: "winrm", auto_correct: true
    config.winrm.password = "vagrant"
    config.winrm.timeout = 21600 # 6 hours
    config.vm.provider "vmware_desktop" do |v|
        v.gui = false
        v.memory = 15786
        v.cpus = 6
        v.vmx["RemoteDisplay.vnc.enabled"] = "true"
        v.vmx["RemoteDisplay.vnc.port"] = "5919"
    end
end
